



import 'package:go_router/go_router.dart';
final GoRouter router =GoRouter(routes: [
  // GoRoute(path:'/',
  // builder: (context,state)=> const  ,
  // ),
  // GoRoute(path:'/Splash2',
  // builder: (context,state)=>const Splash2View() ,
  // ),
  //  GoRoute(path:'/OnBoarding',
  // builder: (context,state)=>const OnBoardingView() ,
  // ),
  // GoRoute(path:"/signUp",
  // builder: (context,state)=>const SignUpView() ,
  // ),
  // GoRoute(path:"/signIn",
  // builder: (context,state)=>const SignInView() ,
  // ),
  // GoRoute(path:"/forgotPassword",
  // builder: (context,state)=>const ForgotPasswordViews() ,
  // ),
  // GoRoute(path:"/doctor",
  // builder: (context,state)=>DoctorView() ,
  // ),
  // GoRoute(path:"/registerYourInformation",
  // builder: (context,state)=>const RegisterYourInformation() ,
  // ),
  // GoRoute(path:"/home",
  // builder: (context,state)=>const HomeViews() ,
  // ),
  // GoRoute(path:"/CustomBtnNavigation",
  // builder: (context,state)=>const CustomBtnNavigation() ,
  // ),
  // GoRoute(path:"/editprofile",
  // builder: (context,state)=>const EditProfileView() ,
  // ),
  // GoRoute(path:"/DescriptionsOfDoctor",
  // builder: (context,state)=>const DescriptionsOfDoctor() ,
  // ),
  // GoRoute(path:"/eatingview",
  // builder: (context,state)=>const EatingView() ,
  // ),
  // GoRoute(path:"/CreateYourMealForm",
  // builder: (context,state)=>const CreateYourMealForm() ,
  // ),
  // GoRoute(path:"/MealSection",
  // builder: (context,state)=>const MealSection() ,
  // ),
  // GoRoute(path:"/WorkoutPlanScreen",
  // builder: (context,state)=>const WorkoutPlanScreen() ,
  // ),
  // GoRoute(path:"/organsView",
  // builder: (context,state)=>const organsView() ,
  // ),
  // GoRoute(path:"/ProfileDoctorView",
  // builder: (context,state)=>const ProfileDoctorView() ,
  // ),
  // GoRoute(path:"/EditProfileDoctor",
  // builder: (context,state)=> EditProfileDoctor() ,
  // ),
  // GoRoute(path:"/MyVerificationPage",
  // builder: (context,state)=>const MyVerificationPage() ,
  // ),
  // GoRoute(path:"/CreateNewPassword",
  // builder: (context,state)=> CreateNewPassword() ,
  // ),
  // GoRoute(path:"/ReminderMedicinsView",
  // builder: (context,state)=>const ReminderMedicinsView() ,
  // ),
  // GoRoute(path:"/PregnancyView",
  // builder: (context,state)=>const PregnancyView() ,
  // ),
  // GoRoute(path:"/ReminderDetailsView",
  // builder: (context,state)=>const ReminderDetailsView() ,
  // ),
  // GoRoute(path:"/ChangeLanguage",
  // builder: (context,state)=>const ChangeLanguage() ,
  // ),
  ]);